site_name: mkdocs-sql
theme:
  name: material
  features:
    - navigation.tabs
    - content.code.copy
    - content.code.select
  icon:
    admonition:
      note: material/table

plugins:
  - search
  - sql:
      databasePath:
        type: sqlite
        path: docs/examples/population.sqlite
      showQuery: false  # Global setting, can be overridden per-page

nav:
  - Home: examples/population.md
  - Examples:
      - Population Data: examples/population.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_css:
  - https://fonts.googleapis.com/icon?family=Material+Icons
